runtime: nodejs10
handlers:
- url: /(.*\..+)$ 
  static_files: dist/\1
  upload: dist/(.*\..+)$
  secure: always
  expiration: 1d
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  expiration: 1d
