import FIELDS from './fields';

export default [
  FIELDS.SLUG,
  FIELDS.NAME,
  FIELDS.DATE,
  FIELDS.ROLE,
  FIELDS.SUBTITLE,
  FIELDS.TOKENS,
  FIELDS.CONTENT,
  FIELDS.TOKENSDARK,
  FIELDS.CREDIT,
];
