name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: yarn run build
    - name: Publish app to Google App Engine
      uses: zxyle/publish-gae-action@v2.3
